//
//  UsePackage.swift
//  firstprj
//
//  Created by 유병찬 on 6/18/24.
//

import SwiftUI
import FabulaItemsProvider

struct UsePackage: View {
    var components = [
        component(name: "P23_Waves", view: AnyView(P23_Waves())),
        component(name: "P227_Bubble", view: AnyView(P227_Bubble())),
        component(name: "P1_Timer", view: AnyView(P1_Timer())),
        component(name: "P2_Drag3D", view: AnyView(P2_Drag3D())),
        component(name: "P3_FlaredRounded", view: AnyView(P3_FlaredRounded())),
        component(name: "P4_FlaredCircle", view: AnyView(P4_FlaredCircle())),
        component(name: "P5_FlaredCapsule", view: AnyView(P5_FlaredCapsule())),
        component(name: "P6_FlaredEllipse", view: AnyView(P6_FlaredEllipse())),
        component(name: "P7_GuideLineModifier", view: AnyView(P7_GuideLineModifier())),
        component(name: "P8_BottomSheet", view: AnyView(P8_BottomSheet())),
        component(name: "P9_RightSheet", view: AnyView(P9_RightSheet())),
        component(name: "P10_CircleTypography", view: AnyView(P10_CircleTypography())),
        component(name: "P11_AngularGradient", view: AnyView(P11_AngularGradient())),
        component(name: "P12_Timeface", view: AnyView(P12_Timeface())),
        component(name: "P13_SKscene", view: AnyView(P13_SKscene())),
        component(name: "P14_Umbrella", view: AnyView(P14_Umbrella())),
        component(name: "P15_3DBoxTypography", view: AnyView(P15_3DBoxTypography())),
        component(name: "P16_CMMotionManager", view: AnyView(P16_CMMotionManager())),
        component(name: "P17_Pyramid", view: AnyView(P17_Pyramid())),
        component(name: "P18_InvertedPyramid", view: AnyView(P18_InvertedPyramid())),
        component(name: "P19_TextWaveProgress", view: AnyView(P19_TextWaveProgress())),
        component(name: "P20_CircularProgress", view: AnyView(P20_CircularProgress())),
        component(name: "P21_FabulaRadioSectionGroup", view: AnyView(P21_FabulaRadioSectionGroup())),
        component(name: "P22_FabulaToggleStyle", view: AnyView(P22_FabulaToggleStyle())),
        component(name: "P23_Waves", view: AnyView(P23_Waves())),
        component(name: "P24_LikeButton", view: AnyView(P24_LikeButton())),
        component(name: "P25_CurveLine", view: AnyView(P25_CurveLine())),
        component(name: "P26_QuadCurveLine", view: AnyView(P26_QuadCurveLine())),
        component(name: "P27_Spring", view: AnyView(P27_Spring())),
        component(name: "P28_StrokePhase", view: AnyView(P28_StrokePhase())),
        component(name: "P29_Alert", view: AnyView(P29_Alert())),
        component(name: "P30_MultipleAlert", view: AnyView(P30_MultipleAlert())),
        component(name: "P31_StaticText", view: AnyView(P31_StaticText())),
        component(name: "P32_TextAlignment", view: AnyView(P32_TextAlignment())),
        component(name: "P33_TextFormat", view: AnyView(P33_TextFormat())),
        component(name: "P34_TextSpacing", view: AnyView(P34_TextSpacing())),
        component(name: "P35_Label", view: AnyView(P35_Label())),
        component(name: "P36_WithAnimation", view: AnyView(P36_WithAnimation())),
        component(name: "P37_ShakeModifier", view: AnyView(P37_ShakeModifier())),
        component(name: "P38_ActionSheet", view: AnyView(P38_ActionSheet())),
        component(name: "P39_ZStackAlignment", view: AnyView(P39_ZStackAlignment())),
        component(name: "P40_VStackAlignment", view: AnyView(P40_VStackAlignment())),
        component(name: "P41_HStackAlignment", view: AnyView(P41_HStackAlignment())),
        component(name: "P42_Angle", view: AnyView(P42_Angle())),
        component(name: "P43_TimelineView", view: AnyView(P43_TimelineView())),
        component(name: "P44_AppStorage", view: AnyView(P44_AppStorage())),
        component(name: "P45_BackgroundStyle", view: AnyView(P45_BackgroundStyle())),
        component(name: "P46_Menu", view: AnyView(P46_Menu())),
        component(name: "P47_ButtonStyle", view: AnyView(P47_ButtonStyle())),
        component(name: "P48_Joystick", view: AnyView(P48_Joystick())),
        component(name: "P49_ButtonStyleConfiguration", view: AnyView(P49_ButtonStyleConfiguration())),
        component(name: "P50_ProgressView", view: AnyView(P50_ProgressView())),
        component(name: "P51_ColorPicker", view: AnyView(P51_ColorPicker())),
        component(name: "P52_DatePicker", view: AnyView(P52_DatePicker())),
        component(name: "P53_ContextMenu", view: AnyView(P53_ContextMenu())),
        component(name: "P54_GroupBox", view: AnyView(P54_GroupBox())),
        component(name: "P55_Picker", view: AnyView(P55_Picker())),
        component(name: "P56_TabView", view: AnyView(P56_TabView())),
        component(name: "P57_TextField", view: AnyView(P57_TextField())),
        component(name: "P58_Toggle", view: AnyView(P58_Toggle())),
        component(name: "P59_DisclosureGroup", view: AnyView(P59_DisclosureGroup())),
        component(name: "P60_Divider", view: AnyView(P60_Divider())),
        component(name: "P61_DragGesture", view: AnyView(P61_DragGesture())),
        component(name: "P62_DropDelegate", view: AnyView(P62_DropDelegate())),
        component(name: "P63_EditButton", view: AnyView(P63_EditButton())),
        component(name: "P64_EmptyModifier", view: AnyView(P64_EmptyModifier())),
        component(name: "P65_EmptyView", view: AnyView(P65_EmptyView())),
        component(name: "P66_Environment", view: AnyView(P66_Environment())),
        component(name: "P67_ControlSize", view: AnyView(P67_ControlSize())),
        component(name: "P68_ControlActiveState", view: AnyView(P68_ControlActiveState())),
        component(name: "P69_IsFocused", view: AnyView(P69_IsFocused())),
        component(name: "P70_IsEnabled", view: AnyView(P70_IsEnabled())),
        component(name: "P71_Calendar", view: AnyView(P71_Calendar())),
        component(name: "P72_RedactionReasons", view: AnyView(P72_RedactionReasons())),
        component(name: "P73_DynamicTypeSize", view: AnyView(P73_DynamicTypeSize())),
        component(name: "P74_DisplayScale", view: AnyView(P74_DisplayScale())),
        component(name: "P75_SizeClass", view: AnyView(P75_SizeClass())),
        component(name: "P76_LayoutDirection", view: AnyView(P76_LayoutDirection())),
        component(name: "P77_Locale", view: AnyView(P77_Locale())),
        component(name: "P78_PixelLength", view: AnyView(P78_PixelLength())),
        component(name: "P79_TimeZone", view: AnyView(P79_TimeZone())),
        component(name: "P80_DefaultMinListRowHeight", view: AnyView(P80_DefaultMinListRowHeight())),
        component(name: "P81_DefaultMinListHeaderHeight", view: AnyView(P81_DefaultMinListHeaderHeight())),
        component(name: "P82_EditMode", view: AnyView(P82_EditMode())),
        component(name: "P83_HeaderProminence", view: AnyView(P83_HeaderProminence())),
        component(name: "P84_ImageScale", view: AnyView(P84_ImageScale())),
        component(name: "P85_SymbolVariants", view: AnyView(P85_SymbolVariants())),
        component(name: "P86_SymbolRenderingMode", view: AnyView(P86_SymbolRenderingMode())),
        component(name: "P87_IsSearching", view: AnyView(P87_IsSearching())),
        component(name: "P88_DismissSearch", view: AnyView(P88_DismissSearch())),
        component(name: "P89_KeyboardShortcut", view: AnyView(P89_KeyboardShortcut())),
        component(name: "P90_Font", view: AnyView(P90_Font())),
        component(name: "P91_LegibilityWeight", view: AnyView(P91_LegibilityWeight())),
        component(name: "P92_MultilineTextAlignment", view: AnyView(P92_MultilineTextAlignment())),
        component(name: "P93_TruncationMode", view: AnyView(P93_TruncationMode())),
        component(name: "P94_LineSpacing", view: AnyView(P94_LineSpacing())),
        component(name: "P95_AllowsTightening", view: AnyView(P95_AllowsTightening())),
        component(name: "P96_LineLimit", view: AnyView(P96_LineLimit())),
        component(name: "P97_MinimumScaleFactor", view: AnyView(P97_MinimumScaleFactor())),
        component(name: "P98_TextCase", view: AnyView(P98_TextCase())),
        component(name: "P99_DisableAutocorrection", view: AnyView(P99_DisableAutocorrection())),
        component(name: "P100_Dismiss", view: AnyView(P100_Dismiss())),
        component(name: "P101_IsPresented", view: AnyView(P101_IsPresented())),
        component(name: "P102_ScenePhase", view: AnyView(P102_ScenePhase())),
        component(name: "P103_OpenURL", view: AnyView(P103_OpenURL())),
        component(name: "P104_Refresh", view: AnyView(P104_Refresh())),
        component(name: "P105_ColorScheme", view: AnyView(P105_ColorScheme())),
        component(name: "P106_BackgroundMaterial", view: AnyView(P106_BackgroundMaterial())),
        component(name: "P107_Toast", view: AnyView(P107_Toast())),
        component(name: "P108_ReverseMask", view: AnyView(P108_ReverseMask())),
        component(name: "P109_CustomStack", view: AnyView(P109_CustomStack())),
        component(name: "P110_ConfirmationDialog", view: AnyView(P110_ConfirmationDialog())),
        component(name: "P111_Sheet", view: AnyView(P111_Sheet())),
        component(name: "P112_FullScreenCover", view: AnyView(P112_FullScreenCover())),
        component(name: "P113_Popover", view: AnyView(P113_Popover())),
        component(name: "P114_Stepper", view: AnyView(P114_Stepper())),
        component(name: "P115_PrimitiveButtonStyle", view: AnyView(P115_PrimitiveButtonStyle())),
        component(name: "P116_ToggleStyle", view: AnyView(P116_ToggleStyle())),
        component(name: "P117_Link", view: AnyView(P117_Link())),
        component(name: "P118_CustomPopup", view: AnyView(P118_CustomPopup())),
        component(name: "P119_EquatableView", view: AnyView(P119_EquatableView())),
        component(name: "P120_ExclusiveGesture", view: AnyView(P120_ExclusiveGesture())),
        component(name: "P121_Form", view: AnyView(P121_Form())),
        component(name: "P122_GeometryReader", view: AnyView(P122_GeometryReader())),
        component(name: "P123_GestureMask", view: AnyView(P123_GestureMask())),
        component(name: "P124_GestureState", view: AnyView(P124_GestureState())),
        component(name: "P125_LinearGradient", view: AnyView(P125_LinearGradient())),
        component(name: "P126_RadialGradient", view: AnyView(P126_RadialGradient())),
        component(name: "P127_Image", view: AnyView(P127_Image())),
        component(name: "P128_ImagePaint", view: AnyView(P128_ImagePaint())),
        component(name: "P129_LabelStyle", view: AnyView(P129_LabelStyle())),
        component(name: "P130_LazyHGrid", view: AnyView(P130_LazyHGrid())),
        component(name: "P131_LazyVGrid", view: AnyView(P131_LazyVGrid())),
        component(name: "P132_LazyHStack", view: AnyView(P132_LazyHStack())),
        component(name: "P133_LazyVStack", view: AnyView(P133_LazyVStack())),
        component(name: "P134_List", view: AnyView(P134_List())),
        component(name: "P135_ListItemTint", view: AnyView(P135_ListItemTint())),
        component(name: "P136_LongPressGesture", view: AnyView(P136_LongPressGesture())),
        component(name: "P137_MagnificationGesture", view: AnyView(P137_MagnificationGesture())),
        component(name: "P138_NavigationLink", view: AnyView(P138_NavigationLink())),
        component(name: "P139_ObservedObject", view: AnyView(P139_ObservedObject())),
        component(name: "P140_OffsetShape", view: AnyView(P140_OffsetShape())),
        component(name: "P141_OutlineGroup", view: AnyView(P141_OutlineGroup())),
        component(name: "P142_PageIndexViewStyle", view: AnyView(P142_PageIndexViewStyle())),
        component(name: "P143_PinnedScrollableViews", view: AnyView(P143_PinnedScrollableViews())),
        component(name: "P144_RotatedShape", view: AnyView(P144_RotatedShape())),
        component(name: "P145_RotationGesture", view: AnyView(P145_RotationGesture())),
        component(name: "P146_ScaledShape", view: AnyView(P146_ScaledShape())),
        component(name: "P147_SceneStorage", view: AnyView(P147_SceneStorage())),
        component(name: "P148_ScrollView", view: AnyView(P148_ScrollView())),
        component(name: "P149_ScrollViewReader", view: AnyView(P149_ScrollViewReader())),
        component(name: "P150_Section", view: AnyView(P150_Section())),
        component(name: "P151_SecureField", view: AnyView(P151_SecureField())),
        component(name: "P152_SequenceGesture", view: AnyView(P152_SequenceGesture())),
        component(name: "P153_SimultaneousGesture", view: AnyView(P153_SimultaneousGesture())),
        component(name: "P154_Slider", view: AnyView(P154_Slider())),
        component(name: "P155_Spacer", view: AnyView(P155_Spacer())),
        component(name: "P156_StateObject", view: AnyView(P156_StateObject())),
        component(name: "P157_StrokeStyle", view: AnyView(P157_StrokeStyle())),
        component(name: "P158_SubscriptionView", view: AnyView(P158_SubscriptionView())),
        component(name: "P159_TapGesture", view: AnyView(P159_TapGesture())),
        component(name: "P160_Text", view: AnyView(P160_Text())),
        component(name: "P161_Namespace", view: AnyView(P161_Namespace())),
        component(name: "P162_ScreenTransition", view: AnyView(P162_ScreenTransition())),
        component(name: "P163_TimingCurve", view: AnyView(P163_TimingCurve())),
        component(name: "P164_Transition", view: AnyView(P164_Transition())),
        component(name: "P165_AnimatablePair", view: AnyView(P165_AnimatablePair())),
        component(name: "P166_TextEditor", view: AnyView(P166_TextEditor())),
        component(name: "P167_ToolBar", view: AnyView(P167_ToolBar())),
        component(name: "P168_TransformedShape", view: AnyView(P168_TransformedShape())),
        component(name: "P169_TupleView", view: AnyView(P169_TupleView())),
        component(name: "P170_ViewBuilder", view: AnyView(P170_ViewBuilder())),
        component(name: "P171_CircleAnimation", view: AnyView(P171_CircleAnimation())),
        component(name: "P172_Rotation3DEffect", view: AnyView(P172_Rotation3DEffect())),
        component(name: "P173_RectangularGraph", view: AnyView(P173_RectangularGraph())),
        component(name: "P174_CustomStepper", view: AnyView(P174_CustomStepper())),
        component(name: "P175_DragGesture", view: AnyView(P175_DragGesture())),
        component(name: "P176_TabSegmentedView", view: AnyView(P176_TabSegmentedView())),
        component(name: "P177_CustomEnvironment", view: AnyView(P177_CustomEnvironment())),
        component(name: "P178_CustomViewModifier", view: AnyView(P178_CustomViewModifier())),
        component(name: "P179_FoldUnfold", view: AnyView(P179_FoldUnfold())),
        component(name: "P180_FoldPaper", view: AnyView(P180_FoldPaper())),
        component(name: "P181_ScrollOffset", view: AnyView(P181_ScrollOffset())),
        component(name: "P182_CurveScroll", view: AnyView(P182_CurveScroll())),
        component(name: "P183_CircularList", view: AnyView(P183_CircularList())),
        component(name: "P184_ShapeIndicator", view: AnyView(P184_ShapeIndicator())),
        component(name: "P185_CircleAlignment", view: AnyView(P185_CircleAlignment())),
        component(name: "P186_RotateGesture", view: AnyView(P186_RotateGesture())),
        component(name: "P187_HierarchyTree", view: AnyView(P187_HierarchyTree())),
        component(name: "P188_LineAnimation", view: AnyView(P188_LineAnimation())),
        component(name: "P189_RadialTree", view: AnyView(P189_RadialTree())),
        component(name: "P190_GlassShape", view: AnyView(P190_GlassShape())),
        component(name: "P191_FractalPattern", view: AnyView(P191_FractalPattern())),
        component(name: "P192_FractalBasic", view: AnyView(P192_FractalBasic())),
        component(name: "P193_FractalMaker", view: AnyView(P193_FractalMaker())),
        component(name: "P194_LinkCurveLine", view: AnyView(P194_LinkCurveLine())),
        component(name: "P195_BoundsPreferenceKey", view: AnyView(P195_BoundsPreferenceKey())),
        component(name: "P196_TextPreferenceKey", view: AnyView(P196_TextPreferenceKey())),
        component(name: "P197_BoundsPreferenceKey", view: AnyView(P197_BoundsPreferenceKey())),
        component(name: "P198_PolygonShape", view: AnyView(P198_PolygonShape())),
        component(name: "P199_CustomFontSize", view: AnyView(P199_CustomFontSize())),
        component(name: "P201_AlamofireBasic", view: AnyView(P201_AlamofireBasic())),
        component(name: "P202_AlamofireRefresh", view: AnyView(P202_AlamofireRefresh())),
        component(name: "P204_ButtonRole", view: AnyView(P204_ButtonRole())),
        component(name: "P205_ButtonStyle", view: AnyView(P205_ButtonStyle())),
        component(name: "P206_ButtonTint", view: AnyView(P206_ButtonTint())),
        component(name: "P207_ButtonControlSize", view: AnyView(P207_ButtonControlSize())),
        component(name: "P208_ButtonBorderShape", view: AnyView(P208_ButtonBorderShape())),
        component(name: "P209_ControlSize", view: AnyView(P209_ControlSize())),
        component(name: "P210_ZoomModifier", view: AnyView(P210_ZoomModifier())),
        component(name: "P211_FrameModifier", view: AnyView(P211_FrameModifier())),
        component(name: "P212_SizeModifier", view: AnyView(P212_SizeModifier())),
        component(name: "P213_Zoomable", view: AnyView(P213_Zoomable())),
        component(name: "P214_TextFieldClear", view: AnyView(P214_TextFieldClear())),
        component(name: "P215_UnsplashProvider", view: AnyView(P215_UnsplashProvider())),
        component(name: "P216_CombineBasic", view: AnyView(P216_CombineBasic())),
        component(name: "P217_Publisher", view: AnyView(P217_Publisher())),
        component(name: "P218_CustomSubscriber", view: AnyView(P218_CustomSubscriber())),
        component(name: "P219_PassthroughSubject", view: AnyView(P219_PassthroughSubject())),
        component(name: "P220_CurrentValueSubject", view: AnyView(P220_CurrentValueSubject())),
        component(name: "P221_Scroller", view: AnyView(P221_Scroller())),
        component(name: "P222_ScrollerExample1", view: AnyView(P222_ScrollerExample1())),
        component(name: "P223_ScrollerExample2", view: AnyView(P223_ScrollerExample2())),
        component(name: "P224_AnimateText", view: AnyView(P224_AnimateText())),
        component(name: "P225_LottieUI", view: AnyView(P225_LottieUI())),
        component(name: "P226_LottieUIScroller", view: AnyView(P226_LottieUIScroller())),
        component(name: "P227_Bubble", view: AnyView(P227_Bubble())),
        component(name: "P228_AxisSheet", view: AnyView(P228_AxisSheet())),
        component(name: "P229_StarShape", view: AnyView(P229_StarShape())),
        component(name: "P230_AxisRatingBar", view: AnyView(P230_AxisRatingBar())),
        component(name: "P231_AxisContribution", view: AnyView(P231_AxisContribution())),
        component(name: "P232_AxisTooltip", view: AnyView(P232_AxisTooltip())),
        component(name: "P233_AxisTabView", view: AnyView(P233_AxisTabView())),
        component(name: "P234_AxisSegmentedView", view: AnyView(P234_AxisSegmentedView())),
        component(name: "P235_TabViewSelected", view: AnyView(P235_TabViewSelected())),
        component(name: "P236_FlatColor", view: AnyView(P236_FlatColor())),
        component(name: "P237_InitialState", view: AnyView(P237_InitialState())),
        component(name: "P238_LimitTextEditor", view: AnyView(P238_LimitTextEditor())),
        component(name: "P239_DynamicTextEditor", view: AnyView(P239_DynamicTextEditor())),
        component(name: "P240_DisableAnimations", view: AnyView(P240_DisableAnimations())),
        component(name: "P241_Mask", view: AnyView(P241_Mask())),
        component(name: "P242_Conditional", view: AnyView(P242_Conditional())),
        component(name: "P243_WarningEffect", view: AnyView(P243_WarningEffect())),
        component(name: "P244_WarningTextEditor", view: AnyView(P244_WarningTextEditor())),
        component(name: "P245_Mirror", view: AnyView(P245_Mirror())),
        component(name: "P246_FabulaItemsInfographic", view: AnyView(P246_FabulaItemsInfographic())),
        component(name: "P247_ScrollViewAlign", view: AnyView(P247_ScrollViewAlign())),
        component(name: "P248_AlignmentID", view: AnyView(P248_AlignmentID())),
        component(name: "P249_DynamicProperty", view: AnyView(P249_DynamicProperty())),
        component(name: "P250_DynamicViewContent", view: AnyView(P250_DynamicViewContent())),
        component(name: "P251_EnvironmentKey", view: AnyView(P251_EnvironmentKey())),
        component(name: "P252_EnvironmentalModifier", view: AnyView(P252_EnvironmentalModifier())),
        component(name: "P253_FocusedValueKey", view: AnyView(P253_FocusedValueKey())),
        component(name: "P254_GeometryEffect", view: AnyView(P254_GeometryEffect())),
        component(name: "P255_DoubleClick", view: AnyView(P255_DoubleClick())),
        component(name: "P256_Conscious", view: AnyView(P256_Conscious())),
        component(name: "P257_InsettableShape", view: AnyView(P257_InsettableShape())),
        component(name: "P258_CustomPreferenceKey", view: AnyView(P258_CustomPreferenceKey())),
        component(name: "P259_TextFieldStyle", view: AnyView(P259_TextFieldStyle())),
        component(name: "P260_PickerStyle", view: AnyView(P260_PickerStyle())),
        component(name: "P261_CircleAnimateText", view: AnyView(P261_CircleAnimateText())),
        component(name: "P262_BarGraph", view: AnyView(P262_BarGraph())),
        component(name: "P263_NavigationBar", view: AnyView(P263_NavigationBar())),
        component(name: "P264_DynamicFontSize", view: AnyView(P264_DynamicFontSize())),
        component(name: "P265_RadioComponent", view: AnyView(P265_RadioComponent())),
        component(name: "P266_ViscosityCanvas", view: AnyView(P266_ViscosityCanvas())),
        component(name: "P267_LazyGridView", view: AnyView(P267_LazyGridView())),
        component(name: "P268_ShareSheet", view: AnyView(P268_ShareSheet())),
        component(name: "P269_UrlLink", view: AnyView(P269_UrlLink())),
        component(name: "P270_HueColorPicker", view: AnyView(P270_HueColorPicker())),
        component(name: "P271_CollapsibleText", view: AnyView(P271_CollapsibleText())),
        component(name: "P272_CollapsibleView", view: AnyView(P272_CollapsibleView())),
        component(name: "P273_ShapeGenerator", view: AnyView(P273_ShapeGenerator())),
        component(name: "P274_RaindropShape", view: AnyView(P274_RaindropShape())),
        component(name: "P275_Raining", view: AnyView(P275_Raining())),
        component(name: "P276_ImageSlider", view: AnyView(P276_ImageSlider())),
        component(name: "P277_DragAndResize", view: AnyView(P277_DragAndResize())),
        component(name: "P278_RotatingPlayingCard", view: AnyView(P278_RotatingPlayingCard())),
        component(name: "P279_CheckboxComponent", view: AnyView(P279_CheckboxComponent())),
        component(name: "P280_SwitchComponent", view: AnyView(P280_SwitchComponent())),
        component(name: "P281_TextSubstringHighlighter", view: AnyView(P281_TextSubstringHighlighter())),
        component(name: "P282_DebouncedText", view: AnyView(P282_DebouncedText())),
//        component(name: "P283_CatchCat", view: AnyView(P283_CatchCat())),
    ]
    var body: some View {
        NavigationView {
            VStack {
                List(components, rowContent: componentView)

                #if os(iOS)
                #elseif os(macOS)
                #endif
            }
        }
        
    }
    
    var CommListView: some View {
        List(components) { item in // .self 는 모든 인스턴스들이 암시적으로 생성하는 프로퍼티
            HStack {
                Text(item.name)
            }
        }
    }
    
    // 클로저를 변수로 정의
    let componentView: (component) -> AnyView = { item in
        AnyView( // AnyView
            HStack {
                NavigationLink(destination: item.view) {
                    Text(item.name)
                }
            }
        )
    }
}

struct component: Identifiable {
    let id = UUID()
    var name: String
    var view: AnyView
}
